name: Automatisation des tests DevSecOps

on: push

jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
  
      - name: Scan des dépendances (requirements.txt)
        run: |
          docker run --rm \
            -v "$PWD":/project \
            -v "$HOME/.cache/trivy":/root/.cache/ \
            aquasec/trivy:latest fs \
            --scanners vuln \
              --file-patterns "python:requirements.txt" \
              --exit-code 1 \
              --severity HIGH,CRITICAL \
              /project/
              
  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Scan du Dockerfile avec Trivy
        run: |
          docker run --rm \
            -v "$PWD":/project \
            -v "$HOME/.cache/trivy":/root/.cache/ \
            aquasec/trivy:latest config \
              --exit-code 1 \
              --severity HIGH,CRITICAL \
              /project

  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien à faire ici. Votre application est prête à être déployée"
